language: python
python:
    - "2.5"
    - "2.6"
    - "2.7"
    - "pypy"
install:
    - "pip install --use-mirrors -r test-reqs.txt"
    - "pip install --use-mirrors ."
script: python -m potpy.test.runtests
